# GlobalShop 全局拍卖行插件配置文件
# 本配置文件包含插件的所有设置选项，修改后需重启服务器或使用/ah reload命令生效

# 数据库配置
database:
  # 数据库类型，目前仅支持sqlite
  type: sqlite
  # 数据库文件名，存储在plugins/GlobalShop/目录下
  file: data.db

# 经济系统配置
economy:
  # 买家税率（购买物品时需支付的额外费用百分比）
  # 范围: 0.0-1.0，0表示不收税，0.02表示收取2%的税
  buyer_tax_rate: 0.02
  
  # Vault经济系统配置（金币）
  vault:
    # 货币名称，显示在GUI界面和消息中
    name: "金币"
    # 货币符号，显示在价格前面，支持颜色代码
    symbol: "§6$"
    # 交易手续费比例，卖家出售物品时收取的费用百分比
    # 范围: 0.0-1.0，0.05表示收取5%的手续费
    fee: 0.05
    # 最低手续费金额，即使按比例计算的手续费低于此值，也会收取此金额
    min_fee: 1.0
    # 最低加价比例，竞价时最少需要加价的百分比
    # 范围: 0.0-1.0，0.05表示至少加价5%
    min_bid_rate: 0.05
    # 最低加价金额，竞价时最少需要加价的金额
    min_bid_amount: 1.0
  
  # PlayerPoints点券系统配置（点券）
  points:
    # 点券名称，显示在GUI界面和消息中
    name: "点券"
    # 点券符号，显示在价格前面，支持颜色代码
    symbol: "§b♦"
    # 点券交易手续费比例，卖家出售物品时收取的费用百分比
    # 范围: 0.0-1.0，0.05表示收取5%的手续费
    fee: 0.05
    # 点券最低手续费金额，即使按比例计算的手续费低于此值，也会收取此金额
    min_fee: 1.0
    # 点券最低加价比例，竞价时最少需要加价的百分比
    # 范围: 0.0-1.0，0.05表示至少加价5%
    min_bid_rate: 0.05
    # 点券最低加价金额，竞价时最少需要加价的金额
    min_bid_amount: 1.0

# 拍卖配置
auction:
  # 默认拍卖持续时间（秒），上架物品的有效期
  # 86400秒 = 24小时
  default_duration: 86400
  # 最短拍卖时间（秒），不能设置比这个更短的拍卖时间
  # 3600秒 = 1小时
  min_duration: 3600
  # 最长拍卖时间（秒），不能设置比这个更长的拍卖时间
  # 604800秒 = 7天
  max_duration: 604800
  # 每个玩家最大上架数量，超过此数量将无法继续上架物品
  max_listings_per_player: 3
  # 检查过期拍卖的间隔时间（秒）
  # 30秒 = 每30秒检查一次过期拍卖
  check_interval: 30

# GUI界面配置
gui:
  # 拍卖行GUI标题，支持颜色代码
  title: "§8[§6拍卖行§8]"
  # GUI大小，必须是9的倍数，最大值为54（6行*9列）
  size: 54 