name: GlobalShop
version: '${project.version}'
main: cn.i7mc.globalshop.GlobalShop
api-version: '1.21'
depend: [Vault, PlayerPoints]
authors: [Saga]
description: 一个功能强大的Minecraft拍卖行插件
commands:
  auction:
    description: 拍卖行主命令
    usage: /<command> [help|sell|search|my]
    aliases: [ah,gs]

permissions:
  globalshop.use:
    description: 允许使用拍卖行基础功能
    default: true
  globalshop.sell:
    description: 允许上架物品
    default: true
  globalshop.buy:
    description: 允许购买物品
    default: true
  globalshop.admin:
    description: 允许使用管理员命令
    default: op