name: GlobalShop
version: '1.4.0.5'
main: cn.i7mc.globalshop.GlobalShop
api-version: '1.20'
depend: [Vault]
softdepend: [PlayerPoints]
authors: [Saga]
description: 一个功能强大的Minecraft拍卖行插件
commands:
  auction:
    description: 拍卖行主命令
    usage: /<command> [help|sell|search|my]
    aliases: [ah,gs]

permissions:
  globalshop.use:
    description: 允许使用拍卖行基础功能
    default: true
  globalshop.sell:
    description: 允许上架物品
    default: true
  globalshop.buy:
    description: 允许购买物品
    default: true
  globalshop.admin:
    description: 允许使用管理员命令
    default: op
    children:
      globalshop.use: true
      globalshop.sell: true
      globalshop.buy: true
      globalshop.admin.reload: true
      globalshop.admin.close: true
      globalshop.admin.checkexpired: true
      globalshop.admin.hud: true
      globalshop.admin.info: true
  globalshop.admin.reload:
    description: 重新加载配置文件权限
    default: op
  globalshop.admin.close:
    description: 关闭所有拍卖权限
    default: op
  globalshop.admin.checkexpired:
    description: 检查过期物品权限
    default: op
  globalshop.admin.hud:
    description: 允许管理全息拍卖行展示
    default: op
  globalshop.admin.info:
    description: 查询玩家拍卖行信息权限
    default: op